version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: guillermoherrero/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      DOCKER_HOST: 127.0.0.1:2375
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ~/docker-data/italianrestaurant/kafka/docker.sock:/var/run/docker.sock
  discoveryserver:
    image: guillermoherrero/italianrestaurant-discoveryserver
    ports:
      - "8761:8761"
  configserver:
    depends_on:
      - discoveryserver
    image: guillermoherrero/italianrestaurant-configserver
    ports:
      - "8888:8888"
    environment:
      EUREKA_HOSTNAME: discoveryserver
  adminui:
    depends_on:
      - discoveryserver
    image: guillermoherrero/italianrestaurant-adminui
    ports:
      - "9000:9000"
    environment:
      EUREKA_HOSTNAME: discoveryserver
  microservicesdashboard:
    depends_on:
      - discoveryserver
    image: guillermoherrero/italianrestaurant-microservicesdashboard
    ports:
      - "9001:9001"
    environment:
      EUREKA_HOSTNAME: discoveryserver
  waiter:
    depends_on:
      - discoveryserver
      - zookeeper
      - kafka
    image: guillermoherrero/italianrestaurant-waiter
    ports:
      - "8080:8080"
    environment:
      EUREKA_HOSTNAME: discoveryserver
      KAFKA_HOSTNAME: kafka
      ZOOKEEPER_HOSTNAME: zookeeper
#      SPRING_APPLICATION_JSON: '{"spring.cloud.zookeeper.connect-string":"zookeeper:2181"}'
#     SPRING_CLOUD_ZOOKEEPER_CONNECTSTRING: zookeeper:2181
  cook:
    depends_on:
      - discoveryserver
      - zookeeper
      - kafka
    image: guillermoherrero/italianrestaurant-cook
    environment:
      EUREKA_HOSTNAME: discoveryserver
      KAFKA_HOSTNAME: kafka
      ZOOKEEPER_HOSTNAME: zookeeper
#      SPRING_APPLICATION_JSON: '{"spring.cloud.zookeeper.connect-string":"zookeeper:2181"}'      
#      SPRING_CLOUD_ZOOKEEPER_CONNECTSTRING: zookeeper:2181
  menu:
    depends_on:
      - discoveryserver
      - zookeeper
      - kafka
    image: guillermoherrero/italianrestaurant-menu
    environment:
      EUREKA_HOSTNAME: discoveryserver
      KAFKA_HOSTNAME: kafka
      ZOOKEEPER_HOSTNAME: zookeeper
#      SPRING_APPLICATION_JSON: '{"spring.cloud.zookeeper.connect-string":"zookeeper:2181"}'
#      SPRING_CLOUD_ZOOKEEPER_CONNECTSTRING: zookeeper:2181

