version: 2
jobs:
  build:
    machine: true
    working_directory: ~/italianrestaurant
    steps:
    - checkout
  test-eureka:
    steps:
    - run:
        name: Testing Discovery Server
        command: mvn test -f discoveryserver/pom.xml
workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - test-eureka: null
      requires:
      - build