version: 2
jobs:
  
  test-cook:
    machine: true
    working_directory: ~/italianrestaurant
    steps:
    - checkout
    - run:
        name: Install Docker Compose
        command: |
          set -x
          curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
    - run:
        name: Running Kafka with Docker Compose
        command: |
          cd kafka
          docker-compose up -d
    - run:
        name: Testing Cook
        command: mvn test -f cook/pom.xml
  
  deploy-cook:
    machine: true
    working_directory: ~/italianrestaurant
    steps:
    - checkout
    - run:
        name: Deploying Cook
        command: |
          cd cook
          mvn clean package -DskipTests=true
          docker build -t guillermoherrero/italianrestaurant-cook .
          docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" -e="$DOCKER_EMAIL"
          docker push guillermoherrero/italianrestaurant-cook
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-cook
      - deploy-cook:
          requires:
            - test-cook
