version: 2
jobs:
  test-discoveryserver:
    machine: true
    working_directory: ~/italianrestaurant
    steps:
    - checkout
    - run:
        name: Testing Discovery Server
        command: mvn test -f discoveryserver/pom.xml
  test-configserver:
    machine: true
    working_directory: ~/italianrestaurant
    steps:
    - checkout
    - run:
        name: Testing Config Server
        command: mvn test -f configserver/pom.xml
  deploy-discoveryserver:
    machine: true
    working_directory: ~/italianrestaurant
    steps:
    - checkout
    - run:
        name: Deploying Discovery Server
        command: |
          cd discoveryserver
          mvn clean package
          docker build -f Dockerfile -t guillermoherrero/italianrestaurant-discoveryserver .
          docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" -e="$DOCKER_EMAIL"
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-discoveryserver
      - test-configserver
      - deploy-discoveryserver:
          requires:
            - test-discoveryserver