version: 2
jobs:
  test-discoveryserver:
    machine: true
    working_directory: ~/italianrestaurant
    steps:
    - checkout
    - run:
        name: Testing Discovery Server
        command: mvn test -f discoveryserver/pom.xml
  test-configserver:
    machine: true
    working_directory: ~/italianrestaurant
    steps:
    - checkout
    - run:
        name: Testing Config Server
        command: mvn test -f configserver/pom.xml
  
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-discoveryserver
      - test-configserver