spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: ${CONFIGURATION_URI:https://github.com/guillermoherrero/italianrestaurant}
          search-paths:
          - configuration
      discovery:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:8761/eureka/
server:
  port: 8888
