spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIGURATION_URI:https://github.com/guillermoherrero/italianrestaurant}
          search-paths:
          - configuration
      discovery:
        enabled: true
server:
  port: 8888

management:
   security:
        enabled: false