version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: guillermoherrero/italianrestaurant-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      DOCKER_HOST: localhost:2375
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /home/beyondcoding/development/dockerdata/kafka/docker.sock:/var/run/docker.sock
