spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 
            - ${KAFKA_HOSTNAME:localhost}
      bindings:
        orders:
          destination: orders
          content-type: application/json
        dishes:
          destination: dishes
          content-type: application/json
          group: waiters
        requestmenu:
          destination: requestmenu
          content-type: application/json
        menu:
          destination: menu
          content-type: application/json
          group: waiters

server:
  port: 8080
  
waiter:
  name: Mario